version: '2'
services:
  api1-app:
    image: api1
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://api1-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=API1
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 9090:9090
  api1-mongodb:
    extends:
      file: mongodb.yml
      service: api1-mongodb
